version: '3'
services:
  sse:
    build: 
     context: ./
     dockerfile: Dockerfile-node
    ports:
      - 3000:3000
  sse2:
    build: 
     context: ./
     dockerfile: Dockerfile-node2
    ports:
      - 3001:3000
  app:
    build: ./
    ports:
      - "80:80"
    volumes:
      - "./app/:/opt/app"
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"